# Generated by Django 4.1.3 on 2022-11-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_remove_dish_drivers_dish_cooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cook',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
